# Generated by Django 4.1.7 on 2023-03-10 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='datetime',
            new_name='date_time',
        ),
    ]
