# Generated by Django 4.1.7 on 2023-03-10 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_datetime_flight_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='date_time',
            field=models.DateField(),
        ),
    ]
